async (page) => {
  const checks = [];
  const check = (condition, message) => { if (!condition) throw new Error(message); checks.push(message); };
  const counts = () => page.evaluate(() => ["token", "api", "subscription"].map(key => Number(document.getElementById(`${key}-count`).textContent)));
  const tableCount = () => page.locator("#tb-table-body tr").count();
  const selectVersion = async (version, expectedCounts, expectedRows) => {
    await page.locator("#tb-version").selectOption(version);
    await page.waitForFunction(v => document.querySelector('[data-i18n="snapshotLabel"]').textContent === `Terminal-Bench ${v}` && !document.querySelector("#tb-snapshot").disabled, version);
    check(JSON.stringify(await counts()) === JSON.stringify(expectedCounts), `TB ${version} independent coverage`);
    check(await tableCount() === expectedRows, `TB ${version} table rows`);
  };
  check(await page.locator("#recommendations").count() === 0, "Recommendations removed");
  check(JSON.stringify(await counts()) === "[18,18,16]", "TB4 initial coverage");
  check(await tableCount() === 16, "Subscription-first ranking default");
  const initialLayouts = await page.evaluate(() => ["subscription", "api", "token"].map(key => ({metric: key, renderer: document.getElementById(`tb-chart-${key}`).dataset.renderer, ...document.querySelector(`#tb-chart-${key} svg`).dataset})));
  check(initialLayouts.every(item => Number(item.labelCollisions) === 0), "No overview label collisions");
  await page.locator("#tb-min").fill("50");
  check(await tableCount() === 7, "50% success threshold recomputes rows");
  await page.locator("#tb-provider").selectOption("OpenAI");
  check(await tableCount() === 5, "Provider filter combines with threshold");
  await page.locator("#tb-agent").selectOption("Codex");
  check(await tableCount() === 5, "Agent filter combines with provider");
  const percentages = await page.locator("#tb-table-body tr").evaluateAll(rows => ({best: rows[0].children[8].textContent, worst: rows.at(-1).children[7].textContent}));
  check(percentages.best === "100.00%" && percentages.worst === "100.00%", "Filtered cost/value baselines both recalculate");
  await page.locator("#tb-max").fill("40");
  check((await page.locator("#tb-result-count").textContent()).includes("区间"), "Invalid interval displayed explicitly");
  await page.locator("#tb-clear").click();
  await page.locator("#tb-metric").selectOption("api");
  check(await tableCount() === 18, "API ranking includes all measured costs");
  await page.locator("#tb-metric").selectOption("token");
  check(await tableCount() === 18, "Token configuration ranking independent of prices");
  await page.locator("#tb-metric").selectOption("subscription");
  await page.locator("#tb-table-body button").first().click();
  check(await page.locator("#tb-detail").isVisible(), "Raw-record detail opens");
  await page.keyboard.press("Escape");
  check(!await page.locator("#tb-detail").isVisible(), "Raw-record detail closes");
  await page.locator('[data-language="en"]').click();
  check(await page.locator("html").getAttribute("lang") === "en", "English switches in place");
  check(await tableCount() === 16, "Language switch preserves selection and data");
  await page.locator("#tb-card-token").screenshot({path: ".playwright-cli/tb-token-en.png"});
  await selectVersion("3.0", [12, 11, 7], 7);
  await selectVersion("2.1", [22, 22, 18], 18);
  await selectVersion("2.0", [0, 0, 0], 142);
  check(await page.locator("#tb-no-usage").isVisible(), "Legacy missing consumption is explicit");
  await selectVersion("1.0", [0, 0, 0], 62);
  check(await page.locator("#tb-state").getAttribute("data-state") === "frozen", "Legacy versions marked frozen");
  await selectVersion("4.0", [18, 18, 16], 16);
  await page.locator('[data-scenario="general"][role="tab"]').click();
  check(await page.locator("#charts").isVisible(), "AA general archive remains accessible");
  check(JSON.stringify(await counts()) === "[70,66,40]", "AA general snapshot unchanged");
  await page.locator('[data-scenario="coding"][role="tab"]').click();
  check(await page.locator("#coding-charts").isVisible(), "AA coding archive remains accessible");
  check(JSON.stringify(await counts()) === "[52,52,49]", "AA coding snapshot unchanged");
  await page.locator('[data-scenario="terminal"][role="tab"]').click();
  await page.locator('[data-language="zh-CN"]').click();
  await page.locator('[data-motion-choice="reduced"]').click();
  check(await page.locator("html").getAttribute("data-motion") === "reduced", "Reduced motion remains available");
  const chart = page.locator("#tb-chart-subscription");
  await chart.locator("select").first().selectOption("OpenAI");
  check(await chart.locator(".interactive-point").count() === 8, "Chart provider filter");
  await chart.locator(".interactive-point").first().click();
  check(await chart.locator(".is-active-point").count() > 0, "Point selection emphasizes record");
  await chart.locator(".interactive-chart-svg").press("Escape");
  check(await chart.locator(".is-active-point").count() === 0, "Escape clears emphasis");
  await chart.locator(".interactive-zoom-controls button").nth(1).click();
  const zoomLayout = await chart.evaluate(element => ({...element.querySelector("svg").dataset}));
  check(Number(zoomLayout.labelCollisions) === 0, "No label collisions after zoom");
  await chart.locator(".interactive-zoom-controls button").last().click();
  await chart.locator("select").first().selectOption("");
  await page.locator("#tb-rankings").screenshot({path: ".playwright-cli/tb-ranking-zh.png"});
  await page.locator("#tb-card-subscription").screenshot({path: ".playwright-cli/tb-subscription-zh.png"});
  const finalLayouts = await page.evaluate(() => ["subscription", "api", "token"].map(key => ({metric: key, renderer: document.getElementById(`tb-chart-${key}`).dataset.renderer, ...document.querySelector(`#tb-chart-${key} svg`).dataset})));
  check(finalLayouts.every(item => Number(item.labelCollisions) === 0), "Final chart labels collision-free");
  return {checks, initialLayouts, zoomLayout, finalLayouts, url: page.url()};
}
